parameters:
    comur_image_type_class: "Comur\ImageBundle\Form\Type\CroppableImageType"
services:
    comur_image_bundle.image_type:
        class: %comur_image_type_class%
        tags:
            - { name: form.type, alias: comur_image }