parameters:
    comur_image_type_class: "Comur\ImageBundle\Form\Type\CroppableImageType"
services:
    comur_image_bundle.image_type:
        class: %comur_image_type_class%
        tags:
            - { name: form.type, alias: comur_image }
    comur.twig.thumb_extension:
        class: Comur\ImageBundle\Twig\ThumbExtension
        tags:
            - { name: twig.extension }
        arguments: [%comur_image.cropped_image_dir%, %comur_image.thumbs_dir%, "@service_container", %comur_image.web_dirname%]